# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

env:
  global: RGL_USE_NULL=TRUE

r_check_args: "--as-cran --install-args=--build"
warnings_are_errors: false
r_binary_packages:
  - Matrix
  - igraph
  - FNN
  - readr
  - stringr
  - plyr
  - Rvcg

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install libcgal-dev libglu1-mesa-dev mesa-common-dev; fi
  - wget -O travis_helpers.sh http://bit.ly/travis_helpers
  - source travis_helpers.sh
  - rm travis_helpers.sh
  - PACKAGE_NAME=`package_name`
  - PACKAGE_DIRECTORY=`basename ${PWD}`

addons:
  apt:
    packages:
      - mesa-common-dev
      - libglu1-mesa-dev
      - freeglut3-dev
      - libgl1-mesa-dev
