---
title: "Viewing Surfaces I"
author: "Bradley Buchsbaum"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Viewing Surfaces I}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(rgl)
library(neuroim2)
devtools::load_all()
#knitr::knit_hooks$set(webgl = hook_webgl)
inflated_lh_asc <- system.file("testdata", "std.40.lh.inflated.asc", package="neurosurf")
white_lh_asc <- system.file("testdata", "std.40.lh.smoothwm.asc", package="neurosurf")

white_rh_asc <- system.file("testdata", "std.40.rh.smoothwm.asc", package="neurosurf")
inflated_rh_asc <- system.file("testdata", "std.40.rh.inflated.asc", package="neurosurf")

```

## Plotting a Cortical Surface 

```{r} 

white_surf <- read_surf(white_lh_asc)
white_rh_surf <-  read_surf(white_rh_asc)
p <- plot(white_surf)
rglwidget()

```


## Adding a Color Layer to a Surface

Here we add a colors to the surface that are a function of each surface node's `x` coordinate. When then map these values to a `rainbow` color map.

```{r, fig.width=7, fig.height=5} 

white_surf1 <- smooth(white_surf, type="taubin", lambda=.9)

open3d()
xvals <- white_surf1@mesh$vb[1,]
p <- plot(white_surf1, vals=xvals, cmap=rainbow(255))
rglwidget()

```




