---
title: "Viewing Surfaces II"
author: "Bradley Buchsbaum"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Viewing Surfaces II}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(rgl)
library(neuroim2)
devtools::load_all()
#knitr::knit_hooks$set(webgl = hook_webgl)
inflated_lh_asc <- system.file("extdata", "std.8_lh.inflated.asc", package="neurosurf")
white_lh_asc <- system.file("extdata", "std.8_lh.smoothwm.asc", package="neurosurf")

white_rh_asc <- system.file("extdata", "std.8_rh.smoothwm.asc", package="neurosurf")
inflated_rh_asc <- system.file("extdata", "std.8_rh.inflated.asc", package="neurosurf")

white_surf <- read_surf(white_lh_asc)
white_rh_surf <-  read_surf(white_rh_asc)

```

## Showing an activation on a surface

```{r, fig.width=7, fig.height=5} 

white_surf1 <- smooth(white_surf, type="taubin", lambda=.9)

open3d()
mfrow3d(1, 2, byrow = TRUE)
vals <- rnorm(length(nodes(white_surf1)))
surf <- NeuroSurface(white_surf1, indices=1:length(vals), data=vals)
ssurf <- smooth(smooth(surf))
p <- plot(ssurf@geometry, vals=ssurf@data, cmap=rainbow(100), irange=c(-2,2), thresh=c(-.2, .2))

next3d()
comp <- conn_comp(ssurf, threshold=c(-.2,.2))
vals <- ssurf@data
vals[comp$size@data < 5] <- 0
p2 <- plot(ssurf@geometry, vals=vals, cmap=rainbow(100), irange=c(-2,2), thresh=c(-.2, .2))

rglwidget()

```


## Showing an activation overlaid on a curvature map

```{r, fig.width=6, fig.height=5} 

open3d()
white_surf1 <- smooth(white_surf, type="taubin", lambda=.9)
curv <- curvature(white_surf1)

vals <- rnorm(length(nodes(white_surf1)))
surf <- NeuroSurface(white_surf1, indices=1:length(vals), data=vals)
ssurf <- smooth(smooth(surf))
p <- plot(white_surf1, vals=ssurf@data, bgcol=curv_cols(curv),cmap=rainbow(100), irange=c(-2,2), thresh=c(-.3, .3))
rglwidget()

```

