---
title: "Viewing Surfaces III"
author: "Bradley Buchsbaum"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Viewing Surfaces III}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(rgl)
library(neuroim2)
devtools::load_all()
#knitr::knit_hooks$set(webgl = hook_webgl)
inflated_lh_asc <- system.file("testdata", "std.40.lh.inflated.asc", package="neurosurf")
white_lh_asc <- system.file("testdata", "std.40.lh.smoothwm.asc", package="neurosurf")

white_rh_asc <- system.file("testdata", "std.40.rh.smoothwm.asc", package="neurosurf")
inflated_rh_asc <- system.file("testdata", "std.40.rh.inflated.asc", package="neurosurf")

white_surf <- read_surf(white_lh_asc)
white_rh_surf <-  read_surf(white_rh_asc)

```

## Showing two hemisperes in same scene

```{r, fig.width=6, fig.height=5} 

open3d()
white_surf1 <- smooth(white_surf, type="taubin", lambda=.9)

curv_lh <- curvature(white_surf1)
white_rh_surf1 <- smooth(white_rh_surf, type="taubin", lambda=.9)
curv_rh <- curvature(white_rh_surf1)

p <- plot(white_surf1, bgcol=curv_cols(curv_lh), viewpoint="posterior")
p <- plot(white_rh_surf1,bgcol=curv_cols(curv_rh), viewpoint="posterior")
rglwidget()
```


