---
title: "Viewing Surfaces"
author: "Bradley Buchsbaum"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(rgl)
library(neuroim2)
devtools::load_all()
#knitr::knit_hooks$set(webgl = hook_webgl)
inflated_lh_asc <- system.file("testdata", "std.40.lh.inflated.asc", package="neurosurf")
white_lh_asc <- system.file("testdata", "std.40.lh.smoothwm.asc", package="neurosurf")

white_rh_asc <- system.file("testdata", "std.40.rh.smoothwm.asc", package="neurosurf")
inflated_rh_asc <- system.file("testdata", "std.40.rh.inflated.asc", package="neurosurf")

```

## Plotting a Cortical Surface 

```{r} 

white_surf <- read_surf(white_lh_asc)
white_rh_surf <-  read_surf(white_rh_asc)
p <- plot(white_surf)
rglwidget()


```


## Smoothing surface geometry


```{r, fig.width=8, fig.height=5} 


open3d()
layout3d(matrix(1:6, 2,3), heights=c(1,3))
t1 <- text3d(0,0,0,"taubin smooth, lambda=.12"); next3d()
white_surf1 <- smooth(white_surf, type="taubin", lambda=.9)
p1 <- plot(white_surf1); next3d()

t2 <- text3d(0,0,0,"taubin smooth, lambda=.8"); next3d()
white_surf2 <- smooth(white_surf, type="taubin", lambda=.7)
p2 <- plot(white_surf2); next3d()

t3 <- text3d(0,0,0,"taubin smooth, lambda=.4"); next3d()
white_surf3 <- smooth(white_surf, type="taubin", lambda=.5)
p3 <- plot(white_surf3); 

rglwidget()

```

## Adding a Color Layer to a Surface

Here we add a colors to the surface that are a function of each surface node's `x` coordinate. When then map these values to a `rainbow` color map.

```{r, fig.width=7, fig.height=5} 

open3d()
xvals <- white_surf1@mesh$vb[1,]
p <- plot(white_surf1, vals=xvals, cmap=rainbow(255))
rglwidget()

```


## Showing an activation on a surface

```{r, fig.width=7, fig.height=5} 

open3d()
mfrow3d(1, 2, byrow = TRUE)
vals <- rnorm(length(nodes(white_surf1)))
surf <- NeuroSurface(white_surf1, indices=1:length(vals), data=vals)
ssurf <- smooth(smooth(surf))
p <- plot(ssurf@geometry, vals=ssurf@data, cmap=rainbow(100), irange=c(-2,2), thresh=c(-.2, .2))

next3d()
comp <- conn_comp(ssurf, threshold=c(-.2,.2))
vals <- ssurf@data
vals[comp$size@data < 100] <- 0
p2 <- plot(ssurf@geometry, vals=vals, cmap=rainbow(100), irange=c(-2,2), thresh=c(-.2, .2))

rglwidget()

```

## Showing an activation overlaid on a curvature map

```{r, fig.width=7, fig.height=5} 


open3d()
curv <- curvature(white_surf1)

vals <- rnorm(length(nodes(white_surf1)))
surf <- NeuroSurface(white_surf1, indices=1:length(vals), data=vals)
ssurf <- smooth(smooth(surf))


p <- plot(white_surf1, vals=ssurf@data, bgcol=curv_cols(curv),cmap=rainbow(100), irange=c(-2,2), thresh=c(-.3, .3))
rglwidget()

```

## Showing two hemisperes in same scene

```{r, fig.width=7, fig.height=5} 

open3d()
curv_lh <- curvature(white_surf1)

white_rh_surf1 <- smooth(white_rh_surf, type="taubin", lambda=.9)
curv_rh <- curvature(white_rh_surf1)

p <- plot(white_surf1, bgcol=curv_cols(curv_lh), viewpoint="posterior")
p <- plot(white_rh_surf1,bgcol=curv_cols(curv_rh), viewpoint="posterior")
rglwidget()
```

