// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// find_roi_boundaries_cpp
List find_roi_boundaries_cpp(const IntegerMatrix& faces, const IntegerVector& vertex_id);
RcppExport SEXP _neurosurf_find_roi_boundaries_cpp(SEXP facesSEXP, SEXP vertex_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type faces(facesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type vertex_id(vertex_idSEXP);
    rcpp_result_gen = Rcpp::wrap(find_roi_boundaries_cpp(faces, vertex_id));
    return rcpp_result_gen;
END_RCPP
}
// roi_boundary_loops_cpp
List roi_boundary_loops_cpp(const NumericMatrix& vertices, const IntegerMatrix& faces, const IntegerVector& vertex_id);
RcppExport SEXP _neurosurf_roi_boundary_loops_cpp(SEXP verticesSEXP, SEXP facesSEXP, SEXP vertex_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type faces(facesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type vertex_id(vertex_idSEXP);
    rcpp_result_gen = Rcpp::wrap(roi_boundary_loops_cpp(vertices, faces, vertex_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neurosurf_find_roi_boundaries_cpp", (DL_FUNC) &_neurosurf_find_roi_boundaries_cpp, 2},
    {"_neurosurf_roi_boundary_loops_cpp", (DL_FUNC) &_neurosurf_roi_boundary_loops_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_neurosurf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
