// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_hull_world_cpp
NumericMatrix compute_hull_world_cpp(NumericVector vol, IntegerVector dims, NumericMatrix grid2world, double thresh, int n_points, LogicalVector mask);
RcppExport SEXP _neurosurf_compute_hull_world_cpp(SEXP volSEXP, SEXP dimsSEXP, SEXP grid2worldSEXP, SEXP threshSEXP, SEXP n_pointsSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vol(volSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dims(dimsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type grid2world(grid2worldSEXP);
    Rcpp::traits::input_parameter< double >::type thresh(threshSEXP);
    Rcpp::traits::input_parameter< int >::type n_points(n_pointsSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_hull_world_cpp(vol, dims, grid2world, thresh, n_points, mask));
    return rcpp_result_gen;
END_RCPP
}
// estimate_sdf_rigid_cpp
Rcpp::List estimate_sdf_rigid_cpp(const arma::mat& hull_world, Rcpp::NumericVector sdf, Rcpp::IntegerVector sdf_dim, const arma::mat& world2grid_sdf, arma::vec init_par, double outside_penalty, std::string method);
RcppExport SEXP _neurosurf_estimate_sdf_rigid_cpp(SEXP hull_worldSEXP, SEXP sdfSEXP, SEXP sdf_dimSEXP, SEXP world2grid_sdfSEXP, SEXP init_parSEXP, SEXP outside_penaltySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type hull_world(hull_worldSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type sdf(sdfSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type sdf_dim(sdf_dimSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type world2grid_sdf(world2grid_sdfSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type init_par(init_parSEXP);
    Rcpp::traits::input_parameter< double >::type outside_penalty(outside_penaltySEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_sdf_rigid_cpp(hull_world, sdf, sdf_dim, world2grid_sdf, init_par, outside_penalty, method));
    return rcpp_result_gen;
END_RCPP
}
// find_roi_boundaries_cpp
List find_roi_boundaries_cpp(const IntegerMatrix& faces, const IntegerVector& vertex_id);
RcppExport SEXP _neurosurf_find_roi_boundaries_cpp(SEXP facesSEXP, SEXP vertex_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type faces(facesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type vertex_id(vertex_idSEXP);
    rcpp_result_gen = Rcpp::wrap(find_roi_boundaries_cpp(faces, vertex_id));
    return rcpp_result_gen;
END_RCPP
}
// roi_boundary_loops_cpp
List roi_boundary_loops_cpp(const NumericMatrix& vertices, const IntegerMatrix& faces, const IntegerVector& vertex_id);
RcppExport SEXP _neurosurf_roi_boundary_loops_cpp(SEXP verticesSEXP, SEXP facesSEXP, SEXP vertex_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type vertices(verticesSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type faces(facesSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type vertex_id(vertex_idSEXP);
    rcpp_result_gen = Rcpp::wrap(roi_boundary_loops_cpp(vertices, faces, vertex_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_neurosurf_compute_hull_world_cpp", (DL_FUNC) &_neurosurf_compute_hull_world_cpp, 6},
    {"_neurosurf_estimate_sdf_rigid_cpp", (DL_FUNC) &_neurosurf_estimate_sdf_rigid_cpp, 7},
    {"_neurosurf_find_roi_boundaries_cpp", (DL_FUNC) &_neurosurf_find_roi_boundaries_cpp, 2},
    {"_neurosurf_roi_boundary_loops_cpp", (DL_FUNC) &_neurosurf_roi_boundary_loops_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_neurosurf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
