# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' @useDynLib neurosurf, .registration = TRUE
#' @importFrom Rcpp evalCpp
NULL

find_roi_boundaries_cpp <- function(faces, vertex_id) {
    .Call(`_neurosurf_find_roi_boundaries_cpp`, faces, vertex_id)
}

roi_boundary_loops_cpp <- function(vertices, faces, vertex_id) {
    .Call(`_neurosurf_roi_boundary_loops_cpp`, vertices, faces, vertex_id)
}
