# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib neurosurf, .registration = TRUE
#' @importFrom Rcpp sourceCpp
NULL

#' Compute boundary hull points in world space (C++)
#'
#' @param vol flattened numeric array (dim = dims)
#' @param dims integer vector length 3 (nx, ny, nz)
#' @param grid2world 4x4 matrix mapping voxel indices to world coords
#' @param thresh intensity threshold
#' @param n_points max number of hull points (approximate)
#' @param mask optional logical vector same length as vol; if empty, ignored
#'
#' @return numeric matrix (n_points x 3) of (x,y,z) in world coords
compute_hull_world_cpp <- function(vol, dims, grid2world, thresh, n_points, mask) {
    .Call('_neurosurf_compute_hull_world_cpp', PACKAGE = 'neurosurf', vol, dims, grid2world, thresh, n_points, mask)
}

estimate_sdf_rigid_cpp <- function(hull_world, sdf, sdf_dim, world2grid_sdf, init_par, outside_penalty = 20.0, method = "L-BFGS-B") {
    .Call('_neurosurf_estimate_sdf_rigid_cpp', PACKAGE = 'neurosurf', hull_world, sdf, sdf_dim, world2grid_sdf, init_par, outside_penalty, method)
}

find_roi_boundaries_cpp <- function(faces, vertex_id) {
    .Call('_neurosurf_find_roi_boundaries_cpp', PACKAGE = 'neurosurf', faces, vertex_id)
}

roi_boundary_loops_cpp <- function(vertices, faces, vertex_id) {
    .Call('_neurosurf_roi_boundary_loops_cpp', PACKAGE = 'neurosurf', vertices, faces, vertex_id)
}
